name: EN
options:
  developmentLanguage: en
packages:
  CocoaLumberjack:
    path: vendor/CocoaLumberjack
  Lottie:
    path: vendor/lottie-ios
  Reachability:
    path: vendor/Reachability.swift
  SnapKit:
    path: vendor/SnapKit
  SnapshotTesting:
    path: vendor/swift-snapshot-testing
  ZIPFoundation:
    path: vendor/ZIPFoundation
  RxSwift:
    path: vendor/RxSwift
targets:
  EN:
    dependencies:
      - link: false
        target: ENCore
      - target: ENFoundation
    deploymentTarget: '13.5'
    info:
      path: Sources/EN/Resources/Info.plist
      properties:
        LOG_LEVEL: debug
        NETWORK_CONFIGURATION: Test
        GitHash: ""
        BGTaskSchedulerPermittedIdentifiers:
          - $(PRODUCT_BUNDLE_IDENTIFIER).exposure-notification
          - $(PRODUCT_BUNDLE_IDENTIFIER).background-decoy-stop-keys
          - $(PRODUCT_BUNDLE_IDENTIFIER).background-decoy-sequence
          - $(PRODUCT_BUNDLE_IDENTIFIER).background-decoy-register
        CFBundleDisplayName: "🐞 CoronaMelder"
        CFBundleIconName: Media.xcassets/AppIcon.appiconset
        CFBundleName: CoronaMelder
        CFBundleShortVersionString: '1.1.4'
        CFBundleVersion: "1"
        ITSAppUsesNonExemptEncryption: false
        LSApplicationQueriesSchemes:
          - 'https'
        LSRequiresIPhoneOS: true
        NSBluetoothPeripheralUsageDescription: To securely exchange unique id's
        UIAppFonts: []
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UIBackgroundModes:
          - fetch
          - processing
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities:
          - armv7
          - bluetooth-le
          - telephony
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIUserInterfaceStyle: Light
        UIViewControllerBasedStatusBarAppearance: true
        ENDeveloperRegion: TEST_NL_TEST
        ENAPIVersion: 1
    platform: iOS
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: ENCoreTests
          randomExecutionOrder: true
    settings:
      base:
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: C2H38GV99H
        ENABLE_BITCODE: 'YES'
        PRODUCT_BUNDLE_IDENTIFIER: nl.rijksoverheid.en
        SWIFT_OBJC_BRIDGING_HEADER: Sources/EN/AppBridge/EN-Bridging-Header.h
        SWIFT_VERSION: 5.2
        TARGETED_DEVICE_FAMILY: 1
      configs:
        Debug:
          CODE_SIGN_ENTITLEMENTS: Sources/EN/Resources/Entitlements/Debug.entitlements
          CODE_SIGN_IDENTITY: Apple Development
          PROVISIONING_PROFILE_SPECIFIER: CoronaMelder_TST
        Release:
          CODE_SIGN_ENTITLEMENTS: Sources/EN/Resources/Entitlements/Release.entitlements
          CODE_SIGN_IDENTITY: Apple Distribution
          PROVISIONING_PROFILE_SPECIFIER: CoronaMelder_PROD
    sources:
      - path: Sources/EN
    type: application
  ENCore:
    dependencies:
      - target: ENFoundation
      - package: ZIPFoundation
      - package: RxSwift
      - package: SnapKit
      - package: Lottie
      - package: Reachability
      - framework: ExposureNotification.framework
        optional: true
      - framework: vendor/OpenSSL-for-iPhone/openssl.framework
    deploymentTarget: '13.5'
    platform: iOS
    scheme:
      gatherCoverageData: true
      testTargets:
        - name: ENCoreTests
          randomExecutionOrder: true
    settings:
      base:
        OTHER_LDFLAGS: '-weak_framework ExposureNotification'
        PRODUCT_BUNDLE_IDENTIFIER: nl.rijksoverheid.en.core
        SWIFT_OBJC_BRIDGING_HEADER: Sources/ENCore/ObjCBridge.h
        SWIFT_VERSION: 5.2
        TARGETED_DEVICE_FAMILY: 1
    sources:
      - Sources/ENCore
    type: framework
  ENCoreTests:
    dependencies:
      - target: ENCore
      - package: SnapshotTesting
    deploymentTarget: '13.5'
    platform: iOS
    preBuildScripts:
      - name: Generate Mocks
        path: tools/scripts/generate-mocks.sh
    settings:
      base:
        SWIFT_VERSION: 5.2
    sources:
      - Sources/ENCoreTests
    type: bundle.unit-test
  ENFoundation:
    dependencies:
      - package: CocoaLumberjack
        product: CocoaLumberjack
      - package: CocoaLumberjack
        product: CocoaLumberjackSwift
    deploymentTarget: '11.0'
    platform: iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: nl.rijksoverheid.en.foundation
        SWIFT_VERSION: 5.2
        TARGETED_DEVICE_FAMILY: 1
    sources:
      - Sources/ENFoundation
    type: framework
