# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  lane :tests do 
    run_tests(
      scheme: "EN",
      devices: ["iPhone 11"]
    )
  end

  desc "Release master version of CoronaMelder to Firebase"
  lane :release_test_build do 
    tests
    build_app(
      scheme: "EN", 
      configuration: "Debug",
      include_bitcode: true, 
      output_directory: "./.build", 
      export_method: "development"
    )
    firebase_app_distribution(
      app: ENV["FIREBASE_APP_IOS"],
      groups: "ios-latest",
      ipa_path: "./.build/EN.ipa",
      release_notes_file: File.expand_path("release_notes.txt"),
    )
  end
end
 
