#!/bin/sh
if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
  echo "This is a pull request. No deployment will be done."
  exit 0
fi
echo "*********************"
echo "*     Make dev      *"
echo "*********************"
make dev
echo "*********************"
echo "*     Make project  *"
echo "*********************"
make project
