#!/bin/sh
if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
  echo "This is a pull request. No deployment will be done."
  exit 0
fi
echo "*********************"
echo "*      CI tests     *"
echo "*********************"
make dev
