name: test

on:
  pull_request:
    branches:
      - 'main'
      - 'release/**'

jobs:
  test:
    runs-on: macOS-12
    timeout-minutes: 45
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache tools
      uses: ./.github/actions/cache-tools

    - name: Generate TST Project
      env: 
        RELEASE_PROVISIONING_PROFILE: "CoronaMelder_ACC"
        NETWORK_CONFIGURATION: Test
        LOG_LEVEL: debug
        BUNDLE_DISPLAY_NAME: "🐞 CoronaMelder"
        BUNDLE_SHORT_VERSION: tst
        USE_DEVELOPER_MENU: true
        SHARE_LOGS_ENABLED: true
        EN_DEVELOPER_REGION: "TEST_NL_TEST"
      run: |
        ./tools/scripts/pre-build.sh
    - name: Build and test
      run: |
        bundle install
        bundle exec fastlane ios test_ci
